config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  resources :job_application
  root "job_application#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job_application.rb
# == Schema Information
#
# Table name: job_applications
#
#  id               :integer          not null, primary key
#  application_date :date
#  position         :string
#  company          :string
#  platform         :string
#  state            :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class JobApplication < ApplicationRecord
  enum :state, {
    in_process: 1,
    in_interviews: 2,
    in_evaluation: 3,
    rejected: 4,
    hired: 5
  }, default: :in_process

  validates :application_date, presence: true
  validates :position, presence: true
  validates :company, presence: true
  validates :platform, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/job_application_controller.rb
class JobApplicationController < ApplicationController
  def index
    @job_applications = JobApplication.all
  end

  def show
    @job_application =JobApplication.find(params[:id])
  end

  def new; end

  def create; end

  def edit; end

  def update; end

  def destroy; end

  private

end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  def index
    # if JobApplication.all.length.zero?
    #   @job_applications = []
    # end
    # puts "JobApplication.all.inspect: #{JobApplication.all.inspect}"
    @job_applications = JobApplication.all.order(application_date: :desc)
  end

  def show
    @job_application = JobApplication.find(params[:id])
  end

  def new
    @job_application = JobApplication.new
  end

  def create
    @job_application = JobApplication.new(job_application_params)

    if @job_application.save
      redirect_to @job_application
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @job_application = JobApplication.find(params[:id])
  end

  def update
    @job_application = JobApplication.find(params[:id])

    if @job_application.update(job_application_params)
      redirect_to @job_application
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @job_application = JobApplication.find(params[:id])
    puts 'method destroy'
    puts "this is @job_application: #{@job_application.inspect}"
    @job_application.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def job_application_params
    params.require(:job_application).permit(:application_date, 
                                            :application_position, 
                                            :application_company, 
                                            :application_platform, 
                                            :application_state,
                                            :application_capture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_application_helper.rb
module JobApplicationHelper
  def humanized_states(enum_name)
    I18n.t("job_application.attributes.states.#{enum_name}")
  end
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
  def application_state_options
    JobApplication.application_states.map do |key, _v|
      translation = t("enums.job_application.application_states.#{key}")
      [translation, key]
    end
  end

  def application_state_translated(application_state)
    t("enums.job_application.application_state.#{application_state}")
  end
end

app/views/job_application/index.html.erb
<section class="block"><p id="notice"><%= notice %></p></section>
<section class="job-applications block">
  <% if @job_applications %>
    <table>
      <thead class="bg-myorange-500">
      <tr>
        <th>Application date</th>
        <th>Platform</th>
        <th>Company</th>
        <th>Position</th>
        <th>State</th>
        <th colspan="3"></th>
      </tr>
      </thead>
      <tbody>
      <% @job_applications.each do |application| %>
        <tr>
          <td><%= application.application_date %></td>
          <td><%= application.platform %></td>
          <td><%= application.company %></td>
          <td><%= application.position %></td>
          <td><%= humanized_states(application.state) %></td>
          <td><%= link_to 'Show', application %></td>
          <td><%= link_to 'Edit', edit_job_application_path(application) %></td>
          <td><%= link_to 'Delete', application,
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No applications present</p>
  <% end %>
</section>
<section class="block">
  <%= link_to 'New Job Application', new_job_application_path %>
</section>

app/views/job_application/show.html.erb
<section>
  <p><span class="font-bold">Application date:</span> <%= @job_application.application_date %></p>
  <p><span class="font-bold">Position:</span> <%= @job_application.position %></p>
  <p><span class="font-bold">Company:</span> <%= @job_application.company %></p>
  <p><span class="font-bold">Platform:</span> <%= @job_application.platform %></p>
  <p><span class="font-bold">State:</span> <%= humanized_states(@job_application.state) %></p>
</section>

<section>
  <%= link_to 'Back', job_application_index_path %>
</section>

app/views/job_applications/_form.html.erb
<% date_default = job_application.application_date.nil? ? Date.today : job_application.application_date %>
<% button_content = job_application.application_position.nil? ? 'Create Job Application' : 'Update Job Application'%>
<%= form_with(model: job_application, local: true) do |f| %>
  <section>
    <% if job_application.application_capture.present? %>
      <%= image_tag @job_application.application_capture, class: 'application_capture' %>
    <% end %>
    <%= f.file_field :application_capture %>
  </section>

  <% if job_application.application_capture.nil? %>
    <section>
      <%= f.file_field :application_capture %>
    </section>
  <% end %>
  <section>
    <%= f.label :application_date %>
    <%= f.date_field :application_date, value:date_default, required: true %>
    <% @job_application.errors.full_messages_for(:application_date).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </section>
  <section>
    <%= f.label :application_position %>
    <%= f.text_field :application_position, required: true %>
    <% @job_application.errors.full_messages_for(:application_position).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </section>
  <section>
    <%= f.label :application_company %>
    <%= f.text_field :application_company, required: true %>
    <% @job_application.errors.full_messages_for(:application_company).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </section>
  <section>
    <%= f.label :application_platform %>
    <%= f.text_field :application_platform, required: true %>
    <% @job_application.errors.full_messages_for(:application_platform).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </section>
  <section>
    <%= f.label :application_state %>
    <%= f.select :application_state, application_state_options, require: true %>
    <% @job_application.errors.full_messages_for(:application_state).each do |message| %>
      <p><%= message %></p>
    <% end %>
  </section>
  <%= f.submit button_content %>
<% end %>

app/views/job_applications/edit.html.erb
<h2>Edit article <%= @job_application.id %></h2>

<%= render 'form', job_application: @job_application %>

<p><%= link_to "< retornar", job_applications_path %></p>

app/views/job_applications/index.html.erb
<h2>Job Applications</h2>
<div>
  <% @job_applications.each do |application| %>
    <p>
      <%= application.application_date %>, 
      <%= link_to application.application_position, application %>, 
      <%= application.application_company%>, 
      <%= application.application_platform %>, 
      <%= application_state_translated(application.application_state) %>,
      
      <%= link_to "Update", edit_job_application_path(application) %>, 
      <%= link_to "Destroy", job_application_path(application), data: { 
                      turbo_method: :delete, 
                      turbo_confirm: "Are you sure?" 
                    } %></p>
  <% end %>
</div>
<p><%= link_to "New job application", new_job_application_path %></p>
<%# TODO display image existing for each appications %>
<%# TODO display thumbnail that can be scaled %>

app/views/job_applications/new.html.erb
<h2>New Job Application</h2>

<%= render 'form', job_application: @job_application %>

<p><%= link_to "< retornar", job_applications_path %></p>

app/views/job_applications/show.html.erb
<h2>Job Application <%= @job_application.id %></h2>
<div>
  <p>
    <%= @job_application.application_date %>, 
    <%= @job_application.application_position %>, 
    <%= @job_application.application_company %>, 
    <%= @job_application.application_platform %>, 
    <%= application_state_translated(@job_application.application_state) %>
  </p>
  <% if @job_application.application_capture.present? %>
    <section>
      <%= image_tag @job_application.application_capture, class: 'application_capture' %>
    </section>
  <% end %>
</div>
<p>
  <%= link_to "< retornar", job_applications_path %>, 
  <%= link_to "Edit application", edit_job_application_path(@job_application) %>
  <%= link_to "Destroy", job_application_path(@job_application), data: { 
                  turbo_method: :delete, 
                  turbo_confirm: "Are you sure?" 
                } %>
</p>
<%# TODO display thumbnail for image %>
<%# TODO display thumbnail that can be scaled %>

app/views/layouts/_footer.html.erb
<footer class="px-5 flex flex-col">
  <p class="text-center mx-auto">Job Applications Web - &copy; 2025</p>
</footer>

app/views/layouts/_header.html.erb
<header class="px-5 flex flex-col">
  <h1>Job Applications Web</h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "Job Applications Web" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
</head>

<body>
<%= render 'layouts/header' %>

<main class="container mx-auto mt-28 px-5 flex flex-col">
  <%= yield %>
</main>

<%= render 'layouts/footer' %>
</body>
</html>